/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 1.0 Service Pack 2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2010, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <SPIM.h>
#include <LCD.h>
#include <Clock_1.h>
#include <MISO_aliases.h>
#include <MISO.h>
#include <MOSI_aliases.h>
#include <MOSI.h>
#include <SCLK_aliases.h>
#include <SCLK.h>
#include <nSS_aliases.h>
#include <nSS.h>
#include <CapSense.h>
#include <CapSense_CSHL.h>
#include <CapSense_MBX.h>
#include <CapSense_Pins.h>
#include <CapSense_TunerHelper.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <CapSense_CompCH0.h>
#include <CapSense_AMuxCH0.h>
#include <CapSense_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
